### ISSUE TITLE
Should this functionality be in the official extension

### ISSUE THREAD

**Issue by gep13** [wk-j/vscode-cake-runner#2]
Thank you very much for creating this extension, it is a piece of functionality that we have been talking to the vscode team about, as it is something that we would like to see in the official extension as well.

They have plans to change will the build pipeline in VS Code works, to allow for easier integration of external build runners.

In the interim, I think that this functionality would make sense to be included in the official cake extension for vscode.  Would you be interested in combining our efforts, rather than creating two extensions?

**Comment by gep13** [comment]
@wk-j I was just wondering if you had seen the above question.

What do you think?  Thanks!

**Comment by wk-j** [comment]
@gep13  
I'm glad  can you point me how to start?

**Comment by gep13** [comment]
You can find the source code for the official Cake extension here:

https://github.com/cake-build/cake-vscode

If you could make a PR into that repository to include the functionality that you have in this extension, we can get that published, and as a result, not have the duplication of extensions.  What do you think?

/cc @agc93

**Comment by wk-j** [comment]
Its OK.
I might start implement on next weekend.

**Comment by gep13** [comment]
@wk-j thanks again for your work that you did here.  It really helped pave the way that the new functionality in the Cake VSCode Extension now works.

I was wondering if it would sense to remove the Cake Runner extension from the marketplace, so that it doesn't cause any confusion for anyone.

Please let me know if you have any questions.

**Comment by gep13** [comment]
@wk-j how are you? I noticed that you just closed this issue, but I see that the package is still available on the marketplace:

https://marketplace.visualstudio.com/items?itemName=wk-j.cake-runner

Did you decide that it wasn't a good idea to unlist it?  Thanks

**Comment by wk-j** [comment]
Hi @gep13 I still use this package and I want to customize it in my own way, however to avoid confusing people I will add warnings in README to tell people to check official extension first

**Comment by gep13** [comment]
@wk-j makes sense, just wanted to check.

If you don't mind, what customisation are you looking to add?  Is it something that makes sense for the wider community as well?
