### ISSUE TITLE
Cake CLI optional?

### ISSUE THREAD

**Issue by Roemer** [wk-j/vscode-cake-runner#5]
With the latest version (switch to Cake CLI), I need to have Cake installed. Before, the bootstrapper took care of downloading cake.
Would it be possible to allow configuring if the cli (new behavior) or the bootstrapper (old behavior) should be used?
Also why did you switch to the CLI? Is there any benefit?

**Comment by meyerrj** [comment]
I agree with @Roemer,  this Cake CLI requirement change is a breaking change, and it now requires that the VSCode users to also have chocolatey installed to provide the CLI executable.  

The old behavior of using the Bootstrapper was much simpler, and doesn't require additional third party software to be installed to work as expected.

**Comment by wk-j** [comment]
Sorry for the inconvenience, I have fixed this problem in version 0.1.1 by check boostrapper first if not exist the extension will use Cake CLI instead.

**Comment by Roemer** [comment]
Awesome, thanks.
